### ISSUE TITLE
Changes to MAST API

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/jwst_mast_query#33]
a change is being implemented to the MAST API - instead of passing an instrument name we will have to pass instrument/mode or instrument*. This may need updating in this code as well. 

https://outerspace.stsci.edu/display/MASTDOCS/JWST+Instrument+Names

**Comment by bhilbert4** [comment]
Hi Sarah. This was resolved via #31. We haven't prepared a new release yet though. There's still one more PR we are reviewing before we do that. If you want to try out the fix in the meantime, you can clone the repo and install the main branch. If you go that route, let us know if you find any problems.

**Comment by skendrew** [comment]
thanks and thanks for being more on top of this than I am 😌

**Comment by bhilbert4** [comment]
No problem. It broke multiple tools that I work on, so it was easy to diagnose here after working on a fix elsewhere. 😢
