### ISSUE TITLE
Cannot find some instrument data due to mode 

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/jwst_mast_query#34]
This potentially should be considered a MAST issue rather than an issue for this tool; not sure. 

I have discovered that in MAST, for NIRCam coronagraphic data the ‘Instrument’ keyword is set to “NIRCAM/CORON” instead of just NIRCam. On the other hand for MIRI coronagraphy it’s just “MIRI”. In other words the instruments are not treated consistently. 

A practical consequence of this is that jwst_mast_query cannot find or download any NIRCam coronagraphy data, because it searches for “nircam” data, and does not know to also search for “nircam/coron”.

There appear to be similar cases of this for other instruments, for example some data labeled as "NIRSPEC/IFU" which does not show up if you search for NIRSpec data using this tool...

**Comment by bhilbert4** [comment]
We put in a fix for this just a few days ago, but haven't yet made a new release that includes it. We have one more PR we want to get in, and then will be making a release. In the meantime, the main branch of the repo does include the fix. From what I've been told, eventually all data will migrate to the instrument/mode value. It just depends on how long it takes MAST to reprocess all the data for that to happen. Until then, some data will have instrument/mode while others will have the bare instrument name. The fix we put in place should find both though.

**Comment by nespinoza** [comment]
Oh, _thank you_ @mperrin for discovering this. We were going nuts not understanding why our NIRISS/SOSS data was not downloading anymore :)...

**Comment by bhilbert4** [comment]
Resolved by #32 and present in the new release (version 0.0.2).
