### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by eas342** [spacetelescope/jwst_mast_query#48]
I upgraded recently and got the following error:

    (mast_query) % python jwst_query.py --propID 1185 -l 5
    Traceback (most recent call last):
      File "~/jwst_mast_query/jwst_mast_query/jwst_query.py", line 18, in <module>
        from PIL import Image
    ModuleNotFoundError: No module named 'PIL'

`pip install Pillow` solved the problem for me. Maybe that just needs to be in the installation requirements?

**Comment by bhilbert4** [comment]
Good catch! Thanks Everett. I'll add that to setup.py.
