### ISSUE TITLE
No Observations Found

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jwst_mast_query#58]
I am running a previously successful (version 0.0.3) command with the latest version of jwst_mast_query, and it is now failing. I can't figure out what needs to get changed.

````
jwst_download.py -v --config jwst_query.cfg --propID 2666 --outrootdir ./mydownloads/ -l 50 --i miri --obsmode image --token YOUR_TOKEN_HERE --filetypes ‘_uncal.fits’
````

**Comment by bhilbert4** [comment]
I don't see anything obvious there. Can you provide the traceback?

**Comment by orifox** [comment]
There was no traceback. I opened this ticket on behalf of a collaborator. They have since updated their jwst_mast_query, and now they can't reproduce the error either. I assume it was a user error. We can close this ticket.

**Comment by Bhavesh012** [comment]
Hey, I am having this issue now while running a tutorial from spaceKLIP package. I am running this command to download the data:

```
jwst_download.py --propID 1386 -i miri --obsnums 4 5 6 7 8 9 28 29 30 31 --outsubdir data_miri_hd65426/uncal -f uncal
```

But I am getting this error:

```
INSTRUMENT:  miri
obsmode:  [None]
propID:  01386
obsnums:  [4, 5, 6, 7, 8, 9, 28, 29, 30, 31]
INFO: MAST API token accepted, welcome Bhavesh Rajpoot [astroquery.mast.auth]
MJD range: 60596.38482971497 60597.48482972325
No obsmode given. Querying for all files for miri.
WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.discovery_portal]
WARNING!! No observations found!!

################################
NO OBSERVATIONS FOUND! exiting....
################################
############## Nothing selected!!!! exiting...
```

I manually checked on the MAST portal and found that the observations do exist. I also tried defining `obsmode`, but it didn't work. I don't know what I am doing wrong here.

I also tried for another proposal ID and targets, but again faced the same issue.
